version: 0.0
os: linux
files:
  - source: /
    destination: /
permissions:
  - object: /
    pattern: "**"
    owner: www-data
    group: www-data
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: /scripts/getpull.sh
      timeout: 30
      runas: root
  BeforeInstall:
    - location: /scripts/getpull.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /scripts/getpull.sh
      timeout: 300
      runas: www-data
  ApplicationStart:
    - location: /scripts/getpull.sh
      timeout: 30
      runas: root