version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: /scripts/getpull.sh
      timeout: 30
      runas: root
  BeforeInstall:
    - location: /scripts/getpull.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /scripts/getpull.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /scripts/getpull.sh
      timeout: 30
      runas: root